### ISSUE TITLE
Carnwen Sprite and Movement Animations

### ISSUE THREAD

**Issue by garr5000** [garr5000/Moon-Spire#4]
Finish the Carnwen sprite and give it movement animations that can be easily discerned as movement in a certain direction.  Quality is not a significant factor, but the following things need to be apparent at a glance.
1. Which direction Carnwen is facing.
2. Which direction Carnwen is moving.
3. Whether or not Carnwen is moving or standing still.

**Comment by CogPrimus** [comment]
4 unfinished but slightly polished moment directions and static directions have been uploaded

**Comment by CogPrimus** [comment]
Enlarged x4 sprites
